#ifndef QTFTDICHIP_GLOBAL_H
#define QTFTDICHIP_GLOBAL_H

#if defined(QTFTDICHIP_LIBRARY)
#  define QTFTDICHIPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTFTDICHIPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTFTDICHIP_GLOBAL_H
